version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: github.com/prometheus/common
    versions:
    - 0.15.0
    - 0.18.0
    - 0.20.0
  - dependency-name: google.golang.org/api
    versions:
    - 0.37.0
    - 0.38.0
    - 0.40.0
    - 0.41.0
  - dependency-name: github.com/go-openapi/swag
    versions:
    - 0.19.13
    - 0.19.14
  - dependency-name: github.com/go-openapi/spec
    versions:
    - 0.20.2
  - dependency-name: github.com/lib/pq
    versions:
    - 1.9.0
- package-ecosystem: npm
  directory: "/ui"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@vue/test-utils"
    versions:
    - 1.1.2
    - 1.1.3
  - dependency-name: "@antv/data-set"
    versions:
    - 0.11.7
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: handlebars
    versions:
    - 4.7.6
